title: Elsie Basa # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  About Me:
  <div class="about-me">
    <p>
      I am a student pursuing a Master's in Statistics at UC Davis, I am deeply enthusiastic about machine learning. I have 2 years of work experience as a Data Analyst working for a bank in the digital department 

    </p>
  </div>

  <br><br>
  ## Programming Languages:
- Python
- Java
-SQL
- R
  
    

  
  <br><br>
  
  <a href="https://www.linkedin.com/in/elsie-basa-aa6405130/">View My LinkedIn Profile</a> 
  <br><br>
  
    <a href="https://github.com/elsiebasa">View My Github</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
